// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nhom6_DoAnMonHoc.Models;

#nullable disable

namespace Nhom6_DoAnMonHoc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240409051921_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nhom6_DoAnMonHoc.Models.CauHoi", b =>
                {
                    b.Property<int>("Mach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mach"));

                    b.Property<string>("Cauhoi")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Dapan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DapanA")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DapanB")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DapanC")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DapanD")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("DeThiMadt")
                        .HasColumnType("int");

                    b.Property<int>("Madt")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.HasKey("Mach");

                    b.HasIndex("DeThiMadt");

                    b.ToTable("CauHois");
                });

            modelBuilder.Entity("Nhom6_DoAnMonHoc.Models.DeThi", b =>
                {
                    b.Property<int>("Madt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Madt"));

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Soluongcauhoi")
                        .HasMaxLength(200)
                        .HasColumnType("int");

                    b.Property<string>("Tendt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Thoigianthi")
                        .HasColumnType("int");

                    b.HasKey("Madt");

                    b.ToTable("DeThis");
                });

            modelBuilder.Entity("Nhom6_DoAnMonHoc.Models.CauHoi", b =>
                {
                    b.HasOne("Nhom6_DoAnMonHoc.Models.DeThi", "DeThi")
                        .WithMany("CauHois")
                        .HasForeignKey("DeThiMadt");

                    b.Navigation("DeThi");
                });

            modelBuilder.Entity("Nhom6_DoAnMonHoc.Models.DeThi", b =>
                {
                    b.Navigation("CauHois");
                });
#pragma warning restore 612, 618
        }
    }
}
